### ISSUE TITLE
M2 output for "oo" or "o13"

### ISSUE THREAD

**Issue by sommars** [musicman3320/m2r#54] opened 2016-07-04 01:39 UTC
```
> m2("oo")
Starting M2
[1] "$:27436"
```

The expected return value here would be the symbol oo, since there was no earlier output for M2 to look at. There are a number of other ways to get this return. For example:

```
> m2("4")
Starting M2
[1] "4"
> m2("oo")
[1] "$:27436"
```

Here the expected return would be 4. There's something funny going on with the M2 code, and I just don't see it.

**Comment by musicman3320** [comment] 2016-07-04 04:41
I see what is happening.  It is giving the return value from the most recent full command, i.e. the line before the start of the loop.  This is returning the socket connection

The underlying issue here is that `value()` does not count as a separate command, so it does not set the `oo` variable.  Perhaps we can set it manually after each successful call to `value()`?

**Comment by musicman3320** [comment] 2016-11-14 15:44
Currently implemented using `m2o13` etc.  Perhaps we should also add `m2oo`, `m2ooo`, etc?

**Comment by dkahle** [comment] 2016-11-16 23:03
That sounds reasonable, the problem is the unpredictability of outputs on the M2 side...

**Comment by musicman3320** [comment] 2016-11-16 23:21
True, especially now that we call m2() several times whenever we parse.  Closing this until someone requests it.

**Closed by musicman3320** 2016-11-16 23:21 UTC
Labels: feature request
